name: Auto Update

on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Get data
      id: data
      run: |
        echo "##[set-output name=branch;]${GITHUB_REF##*/}"
    - name: Create local changes
      run: |
        current_version=$(head -n1 Dockerfile | sed -e "s/^ARG TSVERSION=//")
        latest_version=$(curl https://pkgs.tailscale.com/stable/ | grep tailscale_ -m 1 | cut -d'_' -f 2)
        if [ "$current_version" != "$latest_version" ]; then
          sed -i "1 s/.*/ARG TSVERSION=$latest_version/" Dockerfile
        fi
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        branch: ${{ steps.data.outputs.branch }}
        message: "Auto Update"
        github_token: ${{ secrets.GITHUB_TOKEN }}